export const popularBirds = [
  'Eurasian Wren',
  'European Robin',
  'Barn Swallow',
  'Common Blackbird',
  'Great Tit',
  'Blue Tit',
  'Chaffinch',
  'House Sparrow',
  'European Starling',
  'Song Thrush',
  'Willow Warbler',
  'Goldfinch',
  'Bullfinch',
  'Long-tailed Tit',
  'Pied Wagtail',
  'White Stork',
  'Black Redstart',
  'Common Redpoll',
  'Fieldfare',
  'Cuckoo',
  'Magpie',
  'Jackdaw',
  'Rook',
  'Carrion Crow',
  'Green Woodpecker',
  'Great Spotted Woodpecker',
  'Kingfisher',
  'Common Chiffchaff',
  'Yellowhammer',
  'Redwing',
  'Wheatear',
  'Whinchat',
  'Swallow',
  'Swift',
  'Buzzard',
  'Kestrel',
  'Sparrowhawk',
  'Osprey',
  'Tawny Owl',
  'Barn Owl',
  'Little Owl',
  'Nuthatch',
  'Treecreeper',
  'Jay',
  'Woodpigeon',
  'Collared Dove',
  'Crested Tit',
  'Coal Tit',
  'Marsh Tit',

  'Bearded Reedling',
  'Bittern',
  'Blackcap',
  'Bluethroat',
  'Brambling',
  "Cetti's Warbler",
  'Common Tern',
  'Common Whitethroat',
  'Corn Bunting',
  'Crane',
  'Dunnock',
  'Egyptian Goose',
  'Firecrest',
  'Gadwall',
  'Garganey',
  'Golden Oriole',
  'Goosander',
  'Great Crested Grebe',
  'Great Egret',
  'Greylag Goose',
  'Lesser Whitethroat',
  'Linnet',
  'Little Grebe',
  'Little Tern',
  'Marsh Harrier',
  'Meadow Pipit',
  'Mute Swan',
  'Northern Lapwing',
  'Peregrine Falcon',
  'Red Kite',
  'Reed Bunting',
  'Reed Warbler',
  'Rock Dove',
  'Ruddy Shelduck',
  'Sedge Warbler',
  'Shelduck',
  'Short-eared Owl',
  'Skylark',
  'Spotted Flycatcher',
  'Stock Dove',
  'Stonechat',
  'Teal',
  'Tree Pipit',
  'Tufted Duck',
  'Water Rail',
  'Wigeon',
  'Wood Sandpiper',
  'Wood Warbler',
  'Woodcock',
]
